def can_build(platform):
	return True

def make_js_header(target, source, env):
	for s in source:
		print(str(s))

		fs = open(str(s), "r");
		fd = open(str(s) + ".h", "w")
		fd.write("/* this file has been generated by SCons, do not edit! */\n")
		fd.write("#ifndef JAVASCRIPT_GLOBALS_H\n")
		fd.write("#define JAVASCRIPT_GLOBALS_H\n\n")
		fd.write("const char* javascript_global_module =\n")

		line = fs.readline()
		while(line):
			line = line.replace('"', '\\"')
			line = line.replace("\n", "\\n")
			fd.write('"' + line + '"\n');
			line = fs.readline();

		fd.write(";\n")
		fd.write("#endif\n")

		fs.close();
		fd.close();

	return None

def configure(env):
	js_header = env.Builder(action=make_js_header, suffix=".js.h", src_suffix=".js")
	env.Append(BUILDERS = {"make_js_header" : js_header} );
