#!/usr/bin/env python

Import('env')

env.add_source_files(env.modules_sources, "*.cpp")

libs = [
	"v8",
	"v8_libbase",
	"v8_libplatform",
	"DbgHelp"
]

env.Append(CPPPATH=["#modules/v8/thirdparty/include"])
env.Append(LIBPATH=["#modules/v8/thirdparty"])
env.Append(LINKFLAGS=[l+".lib" for l in libs])



Export('env')
