#!/usr/bin/env python

Import("env")

files = [
    # "#platform/windows/key_mapping_windows.cpp",
    # "#platform/windows/windows_terminal_logger.cpp",
    "app_uwp.cpp",
    "os_uwp.cpp",
]

prog = env.add_program("#bin/godot", files)
